# Generated by Django 5.2 on 2025-04-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysteries', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
