# Generated by Django 5.2 on 2025-04-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysteries', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatcode',
            name='title',
        ),
    ]
