# Generated by Django 5.2 on 2025-05-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysteries', '0003_remove_cheatcode_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='category',
            field=models.CharField(choices=[('team', 'Team'), ('community', 'Community')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
