# Generated by Django 5.2 on 2025-05-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysteries', '0004_theory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='category',
            field=models.CharField(choices=[('team', 'Team'), ('community', 'Community')], default='community', max_length=20),
        ),
    ]
