# Generated by Django 5.2 on 2025-05-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysteries', '0005_alter_theory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
