# Generated by Django 5.2 on 2025-05-05 18:36

import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysteries', '0006_alter_theory_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='author',
            field=models.CharField(default=django.contrib.auth.base_user.AbstractBaseUser.get_username, max_length=100),
        ),
    ]
