# Generated by Django 5.2 on 2025-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysteries', '0011_alter_theory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='image',
            field=models.ImageField(default='default.png', upload_to='theories/'),
        ),
    ]
