# Generated by Django 5.2 on 2025-05-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysteries', '0013_alter_theory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
