# Generated by Django 5.2 on 2025-05-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysteries', '0014_alter_theory_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory',
            name='likes',
        ),
    ]
