# Generated by Django 5.2 on 2025-05-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysteries', '0015_remove_theory_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory',
            name='tags',
        ),
        migrations.AddField(
            model_name='theory',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
