# Generated by Django 5.2 on 2025-05-13 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysteries', '0016_remove_theory_tags_theory_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
